// Generated by rstantools.  Do not edit by hand.

#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_stage2_shrinkage_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 126> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 112, column 2 to line 113, column 65)",
  " (in 'string', line 114, column 2 to column 39)",
  " (in 'string', line 116, column 2 to column 20)",
  " (in 'string', line 117, column 2 to column 14)",
  " (in 'string', line 120, column 2 to column 18)",
  " (in 'string', line 173, column 2 to column 42)",
  " (in 'string', line 124, column 4 to column 25)",
  " (in 'string', line 123, column 9 to line 125, column 3)",
  " (in 'string', line 122, column 4 to column 20)",
  " (in 'string', line 121, column 21 to line 123, column 3)",
  " (in 'string', line 121, column 2 to line 125, column 3)",
  " (in 'string', line 134, column 4 to line 135, column 68)",
  " (in 'string', line 133, column 33 to line 136, column 3)",
  " (in 'string', line 133, column 9 to line 136, column 3)",
  " (in 'string', line 132, column 4 to column 44)",
  " (in 'string', line 131, column 33 to line 133, column 3)",
  " (in 'string', line 131, column 9 to line 136, column 3)",
  " (in 'string', line 130, column 4 to column 34)",
  " (in 'string', line 129, column 26 to line 131, column 3)",
  " (in 'string', line 129, column 2 to line 136, column 3)",
  " (in 'string', line 147, column 6 to column 70)",
  " (in 'string', line 146, column 39 to line 148, column 5)",
  " (in 'string', line 146, column 11 to line 148, column 5)",
  " (in 'string', line 145, column 6 to column 68)",
  " (in 'string', line 144, column 32 to line 146, column 5)",
  " (in 'string', line 144, column 4 to line 148, column 5)",
  " (in 'string', line 143, column 35 to line 149, column 3)",
  " (in 'string', line 143, column 9 to line 149, column 3)",
  " (in 'string', line 141, column 4 to line 142, column 70)",
  " (in 'string', line 140, column 34 to line 143, column 3)",
  " (in 'string', line 140, column 9 to line 149, column 3)",
  " (in 'string', line 139, column 4 to column 71)",
  " (in 'string', line 138, column 27 to line 140, column 3)",
  " (in 'string', line 138, column 2 to line 149, column 3)",
  " (in 'string', line 158, column 4 to column 21)",
  " (in 'string', line 159, column 4 to column 27)",
  " (in 'string', line 157, column 9 to line 160, column 3)",
  " (in 'string', line 155, column 4 to column 30)",
  " (in 'string', line 156, column 4 to column 21)",
  " (in 'string', line 154, column 21 to line 157, column 3)",
  " (in 'string', line 154, column 2 to line 160, column 3)",
  " (in 'string', line 165, column 11 to column 12)",
  " (in 'string', line 165, column 4 to column 18)",
  " (in 'string', line 167, column 6 to column 74)",
  " (in 'string', line 166, column 19 to line 168, column 5)",
  " (in 'string', line 166, column 4 to line 168, column 5)",
  " (in 'string', line 169, column 4 to column 31)",
  " (in 'string', line 164, column 9 to line 170, column 3)",
  " (in 'string', line 163, column 4 to column 61)",
  " (in 'string', line 162, column 14 to line 164, column 3)",
  " (in 'string', line 162, column 2 to line 170, column 3)",
  " (in 'string', line 71, column 2 to column 17)",
  " (in 'string', line 72, column 2 to column 17)",
  " (in 'string', line 74, column 10 to column 11)",
  " (in 'string', line 74, column 2 to column 15)",
  " (in 'string', line 75, column 8 to column 9)",
  " (in 'string', line 75, column 18 to column 19)",
  " (in 'string', line 75, column 2 to column 23)",
  " (in 'string', line 76, column 8 to column 9)",
  " (in 'string', line 76, column 31 to column 32)",
  " (in 'string', line 76, column 2 to column 36)",
  " (in 'string', line 78, column 2 to column 38)",
  " (in 'string', line 79, column 2 to column 14)",
  " (in 'string', line 80, column 2 to column 25)",
  " (in 'string', line 81, column 2 to column 22)",
  " (in 'string', line 83, column 2 to column 31)",
  " (in 'string', line 84, column 10 to column 25)",
  " (in 'string', line 84, column 2 to column 42)",
  " (in 'string', line 85, column 9 to column 24)",
  " (in 'string', line 85, column 2 to column 38)",
  " (in 'string', line 86, column 18 to column 33)",
  " (in 'string', line 86, column 2 to column 49)",
  " (in 'string', line 88, column 2 to column 13)",
  " (in 'string', line 89, column 2 to column 13)",
  " (in 'string', line 90, column 2 to column 40)",
  " (in 'string', line 93, column 2 to column 40)",
  " (in 'string', line 96, column 2 to column 27)",
  " (in 'string', line 98, column 2 to column 32)",
  " (in 'string', line 99, column 10 to column 26)",
  " (in 'string', line 99, column 2 to column 44)",
  " (in 'string', line 100, column 9 to column 25)",
  " (in 'string', line 100, column 2 to column 40)",
  " (in 'string', line 101, column 18 to column 34)",
  " (in 'string', line 101, column 2 to column 51)",
  " (in 'string', line 103, column 2 to column 23)",
  " (in 'string', line 104, column 2 to column 28)",
  " (in 'string', line 106, column 2 to column 33)",
  " (in 'string', line 107, column 2 to column 31)",
  " (in 'string', line 109, column 2 to column 33)",
  " (in 'string', line 116, column 9 to column 10)",
  " (in 'string', line 117, column 9 to column 10)",
  " (in 'string', line 120, column 9 to column 10)",
  " (in 'string', line 55, column 6 to column 53)",
  " (in 'string', line 53, column 32 to line 56, column 5)",
  " (in 'string', line 53, column 11 to line 56, column 5)",
  " (in 'string', line 52, column 6 to column 15)",
  " (in 'string', line 50, column 32 to line 53, column 5)",
  " (in 'string', line 50, column 11 to line 56, column 5)",
  " (in 'string', line 49, column 6 to column 47)",
  " (in 'string', line 47, column 32 to line 50, column 5)",
  " (in 'string', line 47, column 11 to line 56, column 5)",
  " (in 'string', line 46, column 6 to column 52)",
  " (in 'string', line 44, column 32 to line 47, column 5)",
  " (in 'string', line 44, column 11 to line 56, column 5)",
  " (in 'string', line 43, column 6 to column 56)",
  " (in 'string', line 41, column 32 to line 44, column 5)",
  " (in 'string', line 41, column 11 to line 56, column 5)",
  " (in 'string', line 40, column 6 to column 56)",
  " (in 'string', line 38, column 32 to line 41, column 5)",
  " (in 'string', line 38, column 11 to line 56, column 5)",
  " (in 'string', line 37, column 6 to column 67)",
  " (in 'string', line 35, column 32 to line 38, column 5)",
  " (in 'string', line 35, column 11 to line 56, column 5)",
  " (in 'string', line 34, column 6 to column 53)",
  " (in 'string', line 32, column 25 to line 35, column 5)",
  " (in 'string', line 32, column 4 to line 56, column 5)",
  " (in 'string', line 57, column 4 to column 13)",
  " (in 'string', line 31, column 77 to line 58, column 3)",
  " (in 'string', line 62, column 11 to column 23)",
  " (in 'string', line 62, column 4 to column 29)",
  " (in 'string', line 64, column 6 to column 69)",
  " (in 'string', line 63, column 30 to line 65, column 5)",
  " (in 'string', line 63, column 4 to line 65, column 5)",
  " (in 'string', line 66, column 4 to column 28)",
  " (in 'string', line 61, column 61 to line 67, column 3)"};
template <bool propto__, typename T0__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T2__>>* = nullptr>
stan::promote_args_t<T0__, T2__>
builtin_tau_prior_lpdf(const T0__& tau, const int& prior_code,
                       const std::vector<T2__>& params, std::ostream*
                       pstream__);
template <bool propto__, typename T0__, typename T2__, typename T3__,
          typename T4__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>>* = nullptr>
stan::promote_args_t<T0__, stan::base_type_t<T2__>, stan::base_type_t<T3__>,
  stan::base_type_t<T4__>>
mixture_normal_prior_lpdf(const T0__& x, const int& n_components, const T2__&
                          weights_arg__, const T3__& locs_arg__, const T4__&
                          scales_arg__, std::ostream* pstream__);
template <bool propto__, typename T0__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T2__>>*>
stan::promote_args_t<T0__, T2__>
builtin_tau_prior_lpdf(const T0__& tau, const int& prior_code,
                       const std::vector<T2__>& params, std::ostream*
                       pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T2__>;
  int current_statement__ = 0;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 116;
    if (stan::math::logical_eq(prior_code, 1)) {
      current_statement__ = 114;
      return stan::math::normal_lpdf<false>(tau,
               stan::model::rvalue(params, "params",
                 stan::model::index_uni(1)),
               stan::model::rvalue(params, "params",
                 stan::model::index_uni(2)));
    } else {
      current_statement__ = 113;
      if (stan::math::logical_eq(prior_code, 2)) {
        current_statement__ = 111;
        return stan::math::student_t_lpdf<false>(tau,
                 stan::model::rvalue(params, "params",
                   stan::model::index_uni(3)),
                 stan::model::rvalue(params, "params",
                   stan::model::index_uni(1)),
                 stan::model::rvalue(params, "params",
                   stan::model::index_uni(2)));
      } else {
        current_statement__ = 110;
        if (stan::math::logical_eq(prior_code, 3)) {
          current_statement__ = 108;
          return stan::math::lognormal_lpdf<false>(tau,
                   stan::model::rvalue(params, "params",
                     stan::model::index_uni(4)),
                   stan::model::rvalue(params, "params",
                     stan::model::index_uni(5)));
        } else {
          current_statement__ = 107;
          if (stan::math::logical_eq(prior_code, 4)) {
            current_statement__ = 105;
            return stan::math::inv_gamma_lpdf<false>(tau,
                     stan::model::rvalue(params, "params",
                       stan::model::index_uni(1)),
                     stan::model::rvalue(params, "params",
                       stan::model::index_uni(2)));
          } else {
            current_statement__ = 104;
            if (stan::math::logical_eq(prior_code, 5)) {
              current_statement__ = 102;
              return stan::math::gamma_lpdf<false>(tau,
                       stan::model::rvalue(params, "params",
                         stan::model::index_uni(1)),
                       stan::model::rvalue(params, "params",
                         stan::model::index_uni(2)));
            } else {
              current_statement__ = 101;
              if (stan::math::logical_eq(prior_code, 6)) {
                current_statement__ = 99;
                return stan::math::exponential_lpdf<false>(tau,
                         stan::model::rvalue(params, "params",
                           stan::model::index_uni(1)));
              } else {
                current_statement__ = 98;
                if (stan::math::logical_eq(prior_code, 7)) {
                  current_statement__ = 96;
                  return 0;
                } else {
                  current_statement__ = 95;
                  if (stan::math::logical_eq(prior_code, 8)) {
                    current_statement__ = 93;
                    return stan::math::cauchy_lpdf<false>(tau,
                             stan::model::rvalue(params, "params",
                               stan::model::index_uni(1)),
                             stan::model::rvalue(params, "params",
                               stan::model::index_uni(2)));
                  }
                }
              }
            }
          }
        }
      }
    }
    current_statement__ = 117;
    return 0;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <bool propto__, typename T0__, typename T2__, typename T3__,
          typename T4__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>>*>
stan::promote_args_t<T0__, stan::base_type_t<T2__>, stan::base_type_t<T3__>,
  stan::base_type_t<T4__>>
mixture_normal_prior_lpdf(const T0__& x, const int& n_components, const T2__&
                          weights_arg__, const T3__& locs_arg__, const T4__&
                          scales_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
                             stan::base_type_t<T2__>,
                             stan::base_type_t<T3__>,
                             stan::base_type_t<T4__>>;
  int current_statement__ = 0;
  const auto& weights = stan::math::to_ref(weights_arg__);
  const auto& locs = stan::math::to_ref(locs_arg__);
  const auto& scales = stan::math::to_ref(scales_arg__);
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 119;
    stan::math::validate_non_negative_index("lps", "n_components",
      n_components);
    Eigen::Matrix<local_scalar_t__,-1,1> lps =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_components,
        DUMMY_VAR__);
    current_statement__ = 123;
    for (int j = 1; j <= n_components; ++j) {
      current_statement__ = 121;
      stan::model::assign(lps,
        (stan::math::log(
           stan::model::rvalue(weights, "weights", stan::model::index_uni(j)))
        +
        stan::math::normal_lpdf<false>(x,
          stan::model::rvalue(locs, "locs", stan::model::index_uni(j)),
          stan::model::rvalue(scales, "scales", stan::model::index_uni(j)))),
        "assigning variable lps", stan::model::index_uni(j));
    }
    current_statement__ = 124;
    return stan::math::log_sum_exp(lps);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_stage2_shrinkage final : public model_base_crtp<model_stage2_shrinkage> {
private:
  int G;
  int K;
  Eigen::Matrix<double,-1,1> w_data__;
  std::vector<Eigen::Matrix<double,-1,1>> m;
  std::vector<Eigen::Matrix<double,-1,-1>> L;
  int mu_prior_type;
  double mu_loc;
  double mu_scale;
  double mu_df;
  int mu_n_components;
  Eigen::Matrix<double,-1,1> mu_mix_weights_data__;
  Eigen::Matrix<double,-1,1> mu_mix_locs_data__;
  Eigen::Matrix<double,-1,1> mu_mix_scales_data__;
  double mu_lb;
  double mu_ub;
  int mu_is_truncated;
  int tau_prior_type;
  std::vector<double> tau_params;
  int tau_n_components;
  Eigen::Matrix<double,-1,1> tau_mix_weights_data__;
  Eigen::Matrix<double,-1,1> tau_mix_locs_data__;
  Eigen::Matrix<double,-1,1> tau_mix_scales_data__;
  double tau_lb;
  double tau_ub;
  int custom_prior_type;
  std::vector<double> custom_params;
  int centered;
  Eigen::Map<Eigen::Matrix<double,-1,1>> w{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> mu_mix_weights{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> mu_mix_locs{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> mu_mix_scales{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> tau_mix_weights{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> tau_mix_locs{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> tau_mix_scales{nullptr, 0};
public:
  ~model_stage2_shrinkage() {}
  model_stage2_shrinkage(stan::io::var_context& context__, unsigned int
                         random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_stage2_shrinkage_namespace::model_stage2_shrinkage";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 52;
      context__.validate_dims("data initialization", "G", "int",
        std::vector<size_t>{});
      G = std::numeric_limits<int>::min();
      current_statement__ = 52;
      G = context__.vals_i("G")[(1 - 1)];
      current_statement__ = 52;
      stan::math::check_greater_or_equal(function__, "G", G, 1);
      current_statement__ = 53;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 53;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 53;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("w", "K", K);
      current_statement__ = 55;
      context__.validate_dims("data initialization", "w", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      w_data__ = Eigen::Matrix<double,-1,1>::Constant(K,
                   std::numeric_limits<double>::quiet_NaN());
      new (&w) Eigen::Map<Eigen::Matrix<double,-1,1>>(w_data__.data(), K);
      {
        std::vector<local_scalar_t__> w_flat__;
        current_statement__ = 55;
        w_flat__ = context__.vals_r("w");
        current_statement__ = 55;
        pos__ = 1;
        current_statement__ = 55;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 55;
          stan::model::assign(w, w_flat__[(pos__ - 1)],
            "assigning variable w", stan::model::index_uni(sym1__));
          current_statement__ = 55;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 55;
      stan::math::check_simplex(function__, "w", w);
      current_statement__ = 56;
      stan::math::validate_non_negative_index("m", "K", K);
      current_statement__ = 57;
      stan::math::validate_non_negative_index("m", "G", G);
      current_statement__ = 58;
      context__.validate_dims("data initialization", "m", "double",
        std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(G)});
      m = std::vector<Eigen::Matrix<double,-1,1>>(K,
            Eigen::Matrix<double,-1,1>::Constant(G,
              std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> m_flat__;
        current_statement__ = 58;
        m_flat__ = context__.vals_r("m");
        current_statement__ = 58;
        pos__ = 1;
        current_statement__ = 58;
        for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
          current_statement__ = 58;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 58;
            stan::model::assign(m, m_flat__[(pos__ - 1)],
              "assigning variable m", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 58;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 59;
      stan::math::validate_non_negative_index("L", "K", K);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("L", "G", G);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("L", "G", G);
      current_statement__ = 61;
      context__.validate_dims("data initialization", "L", "double",
        std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(G),
          static_cast<size_t>(G)});
      L = std::vector<Eigen::Matrix<double,-1,-1>>(K,
            Eigen::Matrix<double,-1,-1>::Constant(G, G,
              std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> L_flat__;
        current_statement__ = 61;
        L_flat__ = context__.vals_r("L");
        current_statement__ = 61;
        pos__ = 1;
        current_statement__ = 61;
        for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
          current_statement__ = 61;
          for (int sym2__ = 1; sym2__ <= G; ++sym2__) {
            current_statement__ = 61;
            for (int sym3__ = 1; sym3__ <= K; ++sym3__) {
              current_statement__ = 61;
              stan::model::assign(L, L_flat__[(pos__ - 1)],
                "assigning variable L", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 61;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 61;
      stan::math::check_cholesky_factor(function__, "L", L);
      current_statement__ = 62;
      context__.validate_dims("data initialization", "mu_prior_type", "int",
        std::vector<size_t>{});
      mu_prior_type = std::numeric_limits<int>::min();
      current_statement__ = 62;
      mu_prior_type = context__.vals_i("mu_prior_type")[(1 - 1)];
      current_statement__ = 62;
      stan::math::check_greater_or_equal(function__, "mu_prior_type",
        mu_prior_type, 1);
      current_statement__ = 62;
      stan::math::check_less_or_equal(function__, "mu_prior_type",
        mu_prior_type, 3);
      current_statement__ = 63;
      context__.validate_dims("data initialization", "mu_loc", "double",
        std::vector<size_t>{});
      mu_loc = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 63;
      mu_loc = context__.vals_r("mu_loc")[(1 - 1)];
      current_statement__ = 64;
      context__.validate_dims("data initialization", "mu_scale", "double",
        std::vector<size_t>{});
      mu_scale = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 64;
      mu_scale = context__.vals_r("mu_scale")[(1 - 1)];
      current_statement__ = 64;
      stan::math::check_greater_or_equal(function__, "mu_scale", mu_scale, 0);
      current_statement__ = 65;
      context__.validate_dims("data initialization", "mu_df", "double",
        std::vector<size_t>{});
      mu_df = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 65;
      mu_df = context__.vals_r("mu_df")[(1 - 1)];
      current_statement__ = 65;
      stan::math::check_greater_or_equal(function__, "mu_df", mu_df, 0);
      current_statement__ = 66;
      context__.validate_dims("data initialization", "mu_n_components",
        "int", std::vector<size_t>{});
      mu_n_components = std::numeric_limits<int>::min();
      current_statement__ = 66;
      mu_n_components = context__.vals_i("mu_n_components")[(1 - 1)];
      current_statement__ = 66;
      stan::math::check_greater_or_equal(function__, "mu_n_components",
        mu_n_components, 1);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("mu_mix_weights",
        "mu_n_components", mu_n_components);
      current_statement__ = 68;
      context__.validate_dims("data initialization", "mu_mix_weights",
        "double", std::vector<size_t>{static_cast<size_t>(mu_n_components)});
      mu_mix_weights_data__ = Eigen::Matrix<double,-1,1>::Constant(mu_n_components,
                                std::numeric_limits<double>::quiet_NaN());
      new (&mu_mix_weights)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(mu_mix_weights_data__.data(),
        mu_n_components);
      {
        std::vector<local_scalar_t__> mu_mix_weights_flat__;
        current_statement__ = 68;
        mu_mix_weights_flat__ = context__.vals_r("mu_mix_weights");
        current_statement__ = 68;
        pos__ = 1;
        current_statement__ = 68;
        for (int sym1__ = 1; sym1__ <= mu_n_components; ++sym1__) {
          current_statement__ = 68;
          stan::model::assign(mu_mix_weights, mu_mix_weights_flat__[(pos__ -
            1)], "assigning variable mu_mix_weights",
            stan::model::index_uni(sym1__));
          current_statement__ = 68;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 68;
      stan::math::check_simplex(function__, "mu_mix_weights", mu_mix_weights);
      current_statement__ = 69;
      stan::math::validate_non_negative_index("mu_mix_locs",
        "mu_n_components", mu_n_components);
      current_statement__ = 70;
      context__.validate_dims("data initialization", "mu_mix_locs", "double",
        std::vector<size_t>{static_cast<size_t>(mu_n_components)});
      mu_mix_locs_data__ = Eigen::Matrix<double,-1,1>::Constant(mu_n_components,
                             std::numeric_limits<double>::quiet_NaN());
      new (&mu_mix_locs)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(mu_mix_locs_data__.data(),
        mu_n_components);
      {
        std::vector<local_scalar_t__> mu_mix_locs_flat__;
        current_statement__ = 70;
        mu_mix_locs_flat__ = context__.vals_r("mu_mix_locs");
        current_statement__ = 70;
        pos__ = 1;
        current_statement__ = 70;
        for (int sym1__ = 1; sym1__ <= mu_n_components; ++sym1__) {
          current_statement__ = 70;
          stan::model::assign(mu_mix_locs, mu_mix_locs_flat__[(pos__ - 1)],
            "assigning variable mu_mix_locs", stan::model::index_uni(sym1__));
          current_statement__ = 70;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 71;
      stan::math::validate_non_negative_index("mu_mix_scales",
        "mu_n_components", mu_n_components);
      current_statement__ = 72;
      context__.validate_dims("data initialization", "mu_mix_scales",
        "double", std::vector<size_t>{static_cast<size_t>(mu_n_components)});
      mu_mix_scales_data__ = Eigen::Matrix<double,-1,1>::Constant(mu_n_components,
                               std::numeric_limits<double>::quiet_NaN());
      new (&mu_mix_scales)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(mu_mix_scales_data__.data(),
        mu_n_components);
      {
        std::vector<local_scalar_t__> mu_mix_scales_flat__;
        current_statement__ = 72;
        mu_mix_scales_flat__ = context__.vals_r("mu_mix_scales");
        current_statement__ = 72;
        pos__ = 1;
        current_statement__ = 72;
        for (int sym1__ = 1; sym1__ <= mu_n_components; ++sym1__) {
          current_statement__ = 72;
          stan::model::assign(mu_mix_scales, mu_mix_scales_flat__[(pos__ -
            1)], "assigning variable mu_mix_scales",
            stan::model::index_uni(sym1__));
          current_statement__ = 72;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 72;
      stan::math::check_greater_or_equal(function__, "mu_mix_scales",
        mu_mix_scales, 0);
      current_statement__ = 73;
      context__.validate_dims("data initialization", "mu_lb", "double",
        std::vector<size_t>{});
      mu_lb = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 73;
      mu_lb = context__.vals_r("mu_lb")[(1 - 1)];
      current_statement__ = 74;
      context__.validate_dims("data initialization", "mu_ub", "double",
        std::vector<size_t>{});
      mu_ub = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 74;
      mu_ub = context__.vals_r("mu_ub")[(1 - 1)];
      current_statement__ = 75;
      context__.validate_dims("data initialization", "mu_is_truncated",
        "int", std::vector<size_t>{});
      mu_is_truncated = std::numeric_limits<int>::min();
      current_statement__ = 75;
      mu_is_truncated = context__.vals_i("mu_is_truncated")[(1 - 1)];
      current_statement__ = 75;
      stan::math::check_greater_or_equal(function__, "mu_is_truncated",
        mu_is_truncated, 0);
      current_statement__ = 75;
      stan::math::check_less_or_equal(function__, "mu_is_truncated",
        mu_is_truncated, 1);
      current_statement__ = 76;
      context__.validate_dims("data initialization", "tau_prior_type", "int",
        std::vector<size_t>{});
      tau_prior_type = std::numeric_limits<int>::min();
      current_statement__ = 76;
      tau_prior_type = context__.vals_i("tau_prior_type")[(1 - 1)];
      current_statement__ = 76;
      stan::math::check_greater_or_equal(function__, "tau_prior_type",
        tau_prior_type, 1);
      current_statement__ = 76;
      stan::math::check_less_or_equal(function__, "tau_prior_type",
        tau_prior_type, 10);
      current_statement__ = 77;
      context__.validate_dims("data initialization", "tau_params", "double",
        std::vector<size_t>{static_cast<size_t>(6)});
      tau_params = std::vector<double>(6,
                     std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 77;
      tau_params = context__.vals_r("tau_params");
      current_statement__ = 78;
      context__.validate_dims("data initialization", "tau_n_components",
        "int", std::vector<size_t>{});
      tau_n_components = std::numeric_limits<int>::min();
      current_statement__ = 78;
      tau_n_components = context__.vals_i("tau_n_components")[(1 - 1)];
      current_statement__ = 78;
      stan::math::check_greater_or_equal(function__, "tau_n_components",
        tau_n_components, 1);
      current_statement__ = 79;
      stan::math::validate_non_negative_index("tau_mix_weights",
        "tau_n_components", tau_n_components);
      current_statement__ = 80;
      context__.validate_dims("data initialization", "tau_mix_weights",
        "double", std::vector<size_t>{static_cast<size_t>(tau_n_components)});
      tau_mix_weights_data__ = Eigen::Matrix<double,-1,1>::Constant(tau_n_components,
                                 std::numeric_limits<double>::quiet_NaN());
      new (&tau_mix_weights)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(tau_mix_weights_data__.data(),
        tau_n_components);
      {
        std::vector<local_scalar_t__> tau_mix_weights_flat__;
        current_statement__ = 80;
        tau_mix_weights_flat__ = context__.vals_r("tau_mix_weights");
        current_statement__ = 80;
        pos__ = 1;
        current_statement__ = 80;
        for (int sym1__ = 1; sym1__ <= tau_n_components; ++sym1__) {
          current_statement__ = 80;
          stan::model::assign(tau_mix_weights, tau_mix_weights_flat__[(pos__
            - 1)], "assigning variable tau_mix_weights",
            stan::model::index_uni(sym1__));
          current_statement__ = 80;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 80;
      stan::math::check_simplex(function__, "tau_mix_weights",
        tau_mix_weights);
      current_statement__ = 81;
      stan::math::validate_non_negative_index("tau_mix_locs",
        "tau_n_components", tau_n_components);
      current_statement__ = 82;
      context__.validate_dims("data initialization", "tau_mix_locs",
        "double", std::vector<size_t>{static_cast<size_t>(tau_n_components)});
      tau_mix_locs_data__ = Eigen::Matrix<double,-1,1>::Constant(tau_n_components,
                              std::numeric_limits<double>::quiet_NaN());
      new (&tau_mix_locs)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(tau_mix_locs_data__.data(),
        tau_n_components);
      {
        std::vector<local_scalar_t__> tau_mix_locs_flat__;
        current_statement__ = 82;
        tau_mix_locs_flat__ = context__.vals_r("tau_mix_locs");
        current_statement__ = 82;
        pos__ = 1;
        current_statement__ = 82;
        for (int sym1__ = 1; sym1__ <= tau_n_components; ++sym1__) {
          current_statement__ = 82;
          stan::model::assign(tau_mix_locs, tau_mix_locs_flat__[(pos__ - 1)],
            "assigning variable tau_mix_locs", stan::model::index_uni(sym1__));
          current_statement__ = 82;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 83;
      stan::math::validate_non_negative_index("tau_mix_scales",
        "tau_n_components", tau_n_components);
      current_statement__ = 84;
      context__.validate_dims("data initialization", "tau_mix_scales",
        "double", std::vector<size_t>{static_cast<size_t>(tau_n_components)});
      tau_mix_scales_data__ = Eigen::Matrix<double,-1,1>::Constant(tau_n_components,
                                std::numeric_limits<double>::quiet_NaN());
      new (&tau_mix_scales)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(tau_mix_scales_data__.data(),
        tau_n_components);
      {
        std::vector<local_scalar_t__> tau_mix_scales_flat__;
        current_statement__ = 84;
        tau_mix_scales_flat__ = context__.vals_r("tau_mix_scales");
        current_statement__ = 84;
        pos__ = 1;
        current_statement__ = 84;
        for (int sym1__ = 1; sym1__ <= tau_n_components; ++sym1__) {
          current_statement__ = 84;
          stan::model::assign(tau_mix_scales, tau_mix_scales_flat__[(pos__ -
            1)], "assigning variable tau_mix_scales",
            stan::model::index_uni(sym1__));
          current_statement__ = 84;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 84;
      stan::math::check_greater_or_equal(function__, "tau_mix_scales",
        tau_mix_scales, 0);
      current_statement__ = 85;
      context__.validate_dims("data initialization", "tau_lb", "double",
        std::vector<size_t>{});
      tau_lb = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 85;
      tau_lb = context__.vals_r("tau_lb")[(1 - 1)];
      current_statement__ = 85;
      stan::math::check_greater_or_equal(function__, "tau_lb", tau_lb, 0);
      current_statement__ = 86;
      context__.validate_dims("data initialization", "tau_ub", "double",
        std::vector<size_t>{});
      tau_ub = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 86;
      tau_ub = context__.vals_r("tau_ub")[(1 - 1)];
      current_statement__ = 86;
      stan::math::check_greater_or_equal(function__, "tau_ub", tau_ub, tau_lb);
      current_statement__ = 87;
      context__.validate_dims("data initialization", "custom_prior_type",
        "int", std::vector<size_t>{});
      custom_prior_type = std::numeric_limits<int>::min();
      current_statement__ = 87;
      custom_prior_type = context__.vals_i("custom_prior_type")[(1 - 1)];
      current_statement__ = 87;
      stan::math::check_greater_or_equal(function__, "custom_prior_type",
        custom_prior_type, 0);
      current_statement__ = 88;
      context__.validate_dims("data initialization", "custom_params",
        "double", std::vector<size_t>{static_cast<size_t>(10)});
      custom_params = std::vector<double>(10,
                        std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 88;
      custom_params = context__.vals_r("custom_params");
      current_statement__ = 89;
      context__.validate_dims("data initialization", "centered", "int",
        std::vector<size_t>{});
      centered = std::numeric_limits<int>::min();
      current_statement__ = 89;
      centered = context__.vals_i("centered")[(1 - 1)];
      current_statement__ = 89;
      stan::math::check_greater_or_equal(function__, "centered", centered, 0);
      current_statement__ = 89;
      stan::math::check_less_or_equal(function__, "centered", centered, 1);
      current_statement__ = 90;
      stan::math::validate_non_negative_index("theta_c", "G", G);
      current_statement__ = 91;
      stan::math::validate_non_negative_index("z", "G", G);
      current_statement__ = 92;
      stan::math::validate_non_negative_index("theta", "G", G);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + G + G;
  }
  inline std::string model_name() const final {
    return "model_stage2_shrinkage";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_stage2_shrinkage_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = in__.template read_constrain_lub<local_scalar_t__,
             jacobian__>((mu_is_truncated ? mu_lb : stan::math::negative_infinity(
                                                      )),
             (mu_is_truncated ? mu_ub : stan::math::positive_infinity()),
             lp__);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 2;
      tau = in__.template read_constrain_lub<local_scalar_t__,
              jacobian__>(tau_lb, tau_ub, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> theta_c =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(G, DUMMY_VAR__);
      current_statement__ = 3;
      theta_c = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(G);
      Eigen::Matrix<local_scalar_t__,-1,1> z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(G, DUMMY_VAR__);
      current_statement__ = 4;
      z = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(G);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(G, DUMMY_VAR__);
      current_statement__ = 11;
      if (stan::math::logical_eq(centered, 1)) {
        current_statement__ = 9;
        stan::model::assign(theta, theta_c, "assigning variable theta");
      } else {
        current_statement__ = 7;
        stan::model::assign(theta,
          stan::math::add(mu, stan::math::multiply(tau, z)),
          "assigning variable theta");
      }
      {
        current_statement__ = 20;
        if (stan::math::logical_eq(mu_prior_type, 1)) {
          current_statement__ = 18;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(mu, mu_loc,
                           mu_scale));
        } else {
          current_statement__ = 17;
          if (stan::math::logical_eq(mu_prior_type, 2)) {
            current_statement__ = 15;
            lp_accum__.add(stan::math::student_t_lpdf<propto__>(mu, mu_df,
                             mu_loc, mu_scale));
          } else {
            current_statement__ = 14;
            if (stan::math::logical_eq(mu_prior_type, 3)) {
              current_statement__ = 12;
              lp_accum__.add(mixture_normal_prior_lpdf<false>(mu,
                               mu_n_components, mu_mix_weights, mu_mix_locs,
                               mu_mix_scales, pstream__));
            }
          }
        }
        current_statement__ = 34;
        if (stan::math::logical_lte(tau_prior_type, 8)) {
          current_statement__ = 32;
          lp_accum__.add(builtin_tau_prior_lpdf<false>(tau, tau_prior_type,
                           tau_params, pstream__));
        } else {
          current_statement__ = 31;
          if (stan::math::logical_eq(tau_prior_type, 9)) {
            current_statement__ = 29;
            lp_accum__.add(mixture_normal_prior_lpdf<false>(tau,
                             tau_n_components, tau_mix_weights, tau_mix_locs,
                             tau_mix_scales, pstream__));
          } else {
            current_statement__ = 28;
            if (stan::math::logical_eq(tau_prior_type, 10)) {
              current_statement__ = 26;
              if (stan::math::logical_eq(custom_prior_type, 1)) {
                current_statement__ = 24;
                lp_accum__.add(((-stan::model::rvalue(custom_params,
                                    "custom_params",
                                    stan::model::index_uni(1)) * tau) -
                  stan::math::log((2 *
                    stan::model::rvalue(custom_params, "custom_params",
                      stan::model::index_uni(1))))));
              } else {
                current_statement__ = 23;
                if (stan::math::logical_eq(custom_prior_type, 2)) {
                  current_statement__ = 21;
                  lp_accum__.add(((-stan::model::rvalue(custom_params,
                                      "custom_params",
                                      stan::model::index_uni(1)) *
                    stan::math::log(tau)) -
                    (stan::model::rvalue(custom_params, "custom_params",
                       stan::model::index_uni(2)) / tau)));
                }
              }
            }
          }
        }
        current_statement__ = 41;
        if (stan::math::logical_eq(centered, 1)) {
          current_statement__ = 38;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(theta_c, mu, tau));
          current_statement__ = 39;
          lp_accum__.add(stan::math::std_normal_lpdf<propto__>(z));
        } else {
          current_statement__ = 35;
          lp_accum__.add(stan::math::std_normal_lpdf<propto__>(z));
          current_statement__ = 36;
          lp_accum__.add(stan::math::std_normal_lpdf<propto__>(theta_c));
        }
        current_statement__ = 51;
        if (stan::math::logical_eq(K, 1)) {
          current_statement__ = 49;
          lp_accum__.add(stan::math::multi_normal_cholesky_lpdf<false>(theta,
                           stan::model::rvalue(m, "m",
                             stan::model::index_uni(1)),
                           stan::model::rvalue(L, "L",
                             stan::model::index_uni(1))));
        } else {
          current_statement__ = 42;
          stan::math::validate_non_negative_index("lps", "K", K);
          Eigen::Matrix<local_scalar_t__,-1,1> lps =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
          current_statement__ = 46;
          for (int k = 1; k <= K; ++k) {
            current_statement__ = 44;
            stan::model::assign(lps,
              (stan::math::log(
                 stan::model::rvalue(w, "w", stan::model::index_uni(k))) +
              stan::math::multi_normal_cholesky_lpdf<false>(theta,
                stan::model::rvalue(m, "m", stan::model::index_uni(k)),
                stan::model::rvalue(L, "L", stan::model::index_uni(k)))),
              "assigning variable lps", stan::model::index_uni(k));
          }
          current_statement__ = 47;
          lp_accum__.add(stan::math::log_sum_exp(lps));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_stage2_shrinkage_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      mu = in__.template read_constrain_lub<local_scalar_t__,
             jacobian__>((mu_is_truncated ? mu_lb : stan::math::negative_infinity(
                                                      )),
             (mu_is_truncated ? mu_ub : stan::math::positive_infinity()),
             lp__);
      double tau = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      tau = in__.template read_constrain_lub<local_scalar_t__,
              jacobian__>(tau_lb, tau_ub, lp__);
      Eigen::Matrix<double,-1,1> theta_c =
        Eigen::Matrix<double,-1,1>::Constant(G,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      theta_c = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(G);
      Eigen::Matrix<double,-1,1> z =
        Eigen::Matrix<double,-1,1>::Constant(G,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      z = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(G);
      Eigen::Matrix<double,-1,1> theta =
        Eigen::Matrix<double,-1,1>::Constant(G,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(mu);
      out__.write(tau);
      out__.write(theta_c);
      out__.write(z);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 11;
      if (stan::math::logical_eq(centered, 1)) {
        current_statement__ = 9;
        stan::model::assign(theta, theta_c, "assigning variable theta");
      } else {
        current_statement__ = 7;
        stan::model::assign(theta,
          stan::math::add(mu, stan::math::multiply(tau, z)),
          "assigning variable theta");
      }
      if (emit_transformed_parameters__) {
        out__.write(theta);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      double tau_squared = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      tau_squared = stan::math::square(tau);
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "tau_squared",
        tau_squared, 0);
      out__.write(tau_squared);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = in__.read<local_scalar_t__>();
      out__.write_free_lub((mu_is_truncated ? mu_lb : stan::math::negative_infinity(
                                                        )),
        (mu_is_truncated ? mu_ub : stan::math::positive_infinity()), mu);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 2;
      tau = in__.read<local_scalar_t__>();
      out__.write_free_lub(tau_lb, tau_ub, tau);
      Eigen::Matrix<local_scalar_t__,-1,1> theta_c =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(G, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(theta_c,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(G),
        "assigning variable theta_c");
      out__.write(theta_c);
      Eigen::Matrix<local_scalar_t__,-1,1> z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(G, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(z,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(G),
        "assigning variable z");
      out__.write(z);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "tau", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "theta_c",
        "double", std::vector<size_t>{static_cast<size_t>(G)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "z", "double",
        std::vector<size_t>{static_cast<size_t>(G)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = context__.vals_r("mu")[(1 - 1)];
      out__.write_free_lub((mu_is_truncated ? mu_lb : stan::math::negative_infinity(
                                                        )),
        (mu_is_truncated ? mu_ub : stan::math::positive_infinity()), mu);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 2;
      tau = context__.vals_r("tau")[(1 - 1)];
      out__.write_free_lub(tau_lb, tau_ub, tau);
      Eigen::Matrix<local_scalar_t__,-1,1> theta_c =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(G, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> theta_c_flat__;
        current_statement__ = 3;
        theta_c_flat__ = context__.vals_r("theta_c");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(theta_c, theta_c_flat__[(pos__ - 1)],
            "assigning variable theta_c", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(theta_c);
      Eigen::Matrix<local_scalar_t__,-1,1> z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(G, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> z_flat__;
        current_statement__ = 4;
        z_flat__ = context__.vals_r("z");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
          current_statement__ = 4;
          stan::model::assign(z, z_flat__[(pos__ - 1)],
            "assigning variable z", stan::model::index_uni(sym1__));
          current_statement__ = 4;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(z);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"mu", "tau", "theta_c", "z"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"theta"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"tau_squared"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(G)},
                std::vector<size_t>{static_cast<size_t>(G)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(G)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>> temp{std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "tau");
    for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
      param_names__.emplace_back(std::string() + "theta_c" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
      param_names__.emplace_back(std::string() + "z" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        param_names__.emplace_back(std::string() + "theta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "tau_squared");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "tau");
    for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
      param_names__.emplace_back(std::string() + "theta_c" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
      param_names__.emplace_back(std::string() + "z" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        param_names__.emplace_back(std::string() + "theta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "tau_squared");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta_c\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(G) + "},\"block\":\"parameters\"},{\"name\":\"z\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(G) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(G) + "},\"block\":\"transformed_parameters\"},{\"name\":\"tau_squared\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta_c\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(G) + "},\"block\":\"parameters\"},{\"name\":\"z\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(G) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(G) + "},\"block\":\"transformed_parameters\"},{\"name\":\"tau_squared\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((1 + 1) + G) + G);
    const size_t num_transformed = emit_transformed_parameters * (G);
    const size_t num_gen_quantities = emit_generated_quantities * (1);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((1 + 1) + G) + G);
    const size_t num_transformed = emit_transformed_parameters * (G);
    const size_t num_gen_quantities = emit_generated_quantities * (1);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_stage2_shrinkage_namespace::model_stage2_shrinkage;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_stage2_shrinkage_namespace::profiles__;
}
#endif
#endif
